# -*- coding: utf-8 -*-
"""Labsheet3.0121

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q1DkFqUaKYCuRtAbj1yVq-lDlJ7xdVYx
"""

# Import necessary library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns # data visualization

# Importing the dataset
df=pd.read_csv('/content/archive.zip')
df.head(10)

df.info()

print(df.shape)

print(df.describe())

# Outlier Analysis
fig, axs = plt.subplots(3, figsize = (5,5))
plt.subplots_adjust(hspace = .5)
sns.boxplot(df['TV'], ax = axs[0])
sns.boxplot(df['Radio'], ax = axs[1])
sns.boxplot(df['Newspaper'], ax = axs[2])
plt.tight_layout()

# declare feature variable and target variable
x=df['TV']
y=df['Sales']

plt.scatter(x,y,color = 'blue' ,label='scatter plot')
plt.title('relationship between TV ads and Sales')
plt.xlabel('TV ads')
plt.ylabel('sales')
plt.legend()
plt.show()

print(x.shape)
print(y.shape)

x=np.array(x)
y=np.array(y)

x=x.reshape(-1,1)
y=y.reshape(-1,1)

print(x.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression
lm=LinearRegression()

lm.fit(x_train,y_train)

y_pred=lm.predict(x_test)

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,lm.predict(x_train),color='blue')

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,lm.predict(x_train),color='blue')
plt.title('Test set result')
plt.xlabel('TV')
plt.ylabel('sales')
plt.show()

slope = lm.coef_
intercept = lm.intercept_,
print("estimate model slope:",slope)
print("estimate model intercept:",intercept)

x_new=[[200]]

lm.predict(x_new)

