# -*- coding: utf-8 -*-
"""Labsheet1.0121

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdwBegp_rsvEZTKfrU3HACon4HMYH9u5
"""

#code to print all the keywords present in the python
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

l1=[1,2,3,4,5,6]
for x in l1:
  print(x)

len(l1)

l1.append(7)

print(l1)

l2=[8,9]

l3=l1+l2
l3

l1=[1,1,1,2,2,2,3,3,3,4,4]

l2=[]
for x in l1:
  if x not in l2:
    l2.append(x)
l2

l2=list(set(l1))
l2

a=10
b=1.5
c='abc'

print(type(a),type(b),type(c))

for x in range(6):
  print(x)

#slicing
l1=[1,2,3,4,5,6,7,8]
print(l1[:4])

l1[-1] #printing the last element

l1[::-1] #reversing the list

str1=input("Enter a string:")
str2=str1[::-1]

if str1==str2:
  print("The string is a Palindrome:")
else:
  print("The string is not a Plaindrome")

import random
numbers=[1,2,3,4,5,6,7,8]
random.shuffle(numbers)
print(numbers)

num=[1,2,3,4,5,6,7,8,9]
sum(num)

#Membership operator
days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]
"Wednesday" in days

"Friday" not in days

nums=[1,2,3,4,5,6,7,8,9,1,2]
print(nums)

nums.count(2)

list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

list=["red","Orange","black","Blue"]
print(list)
list.clear()
list

a=["a","b","c","d"]
print(a)
a.append("e")
print(a)

nums=[1,2,3,1,5,6,7,8,5,2,1]
print(nums)
nums.count(1)

list_1=[1,2,3,4]
print(list_1)
list_2=list_1.copy()
print(list_2)

list_1=[1,2,3,4]
b=[5,6,7,8]
list_1.extend(b)
print(list_1)

#Tuples
a=(4)
print(type(a))
b=(5,)
print(type(b))

a=(1,2,3,4,4.5,5.5,2.6)
print(a)

c=("one","two","three")
c

mix=("HII",70256,66.5)
print(mix)
print(mix[0])

#Dictionary
a={"name":"Amulya",
   "Class":"5CIT03",
   "Program":"CSE"}
print(a)

len(a)

type(a)

x=a.keys()
print(x)
y=a.values()
print(y)

z=a.items()
z

#Sets

s1={1,2,3,4}
print(s1)

number={1,2,3,1,5,6,7,8,5,2,1}
print(number)

print(len(number))
print(type(number))

#Functions
def add():
  a=2
  b=3
  sum=a+b
  return sum
add()
print(add())